### ISSUE TITLE
FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot read property 'tokens/hashtags' of null

### ISSUE THREAD

**Issue by MrGoogol** [sararob/ml-talk-demos#6]
In nl-firebase-twitter demo, backend portion, the "tweetRef.on('value', function (snap) {" block seems to create the errors with tokens/hashtags. Please mention if you know the solution. Thank you.

**Comment by sararob** [comment]
Super delayed response but this is fixed in the latest commit
